apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir-api-deployment
spec:
  selector:
    matchLabels:
      app: fhirapi
  replicas: 2
  template:
    metadata:
      labels:
        app: fhirapi
    spec:
      containers:
      - name:arcadia-fhir-api
        image: 498769975733.dkr.ecr.us-east-1.amazonaws.com/arcadia.io/arcadia-fhir-api
        ports:
        - containerPort: 8081
