apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhirapi-deployment
spec:
  selector:
    matchLabels:
      app: fhirapi
  replicas: 2
  template:
    metadata:
      labels:
        app: fhirapi
    spec:
      containers:
      - name: fhirapi
        image: 498769975733.dkr.ecr.us-east-1.amazonaws.com/arcadia.io/arcadia-fhir-api:20220422-22e824a
        ports:
        - containerPort: 8081



